### ISSUE TITLE
[feature request] Frontend form radio and checkbox customization

### ISSUE THREAD

**Issue by jmarceli** [elliotcondon/acf#578]
Customizing radio and checkboxes in the frontend form require targeting some element which follows `:checked` checkbox or radio (in order to use `input:checked + tag_name` CSS selector`.

SO topic: http://stackoverflow.com/questions/4148499/how-to-style-checkbox-using-css

Working tutorial: https://webdesign.tutsplus.com/articles/quick-tip-easy-css3-checkboxes-and-radio-buttons--webdesign-8953

Unfortunately, in ACF (version 5.4.2) there is no element after these inputs which makes custom styling impossible to do.

The solution is simple: add empty `<span></span>` after each radio or checkbox input. This is not possible with existing filters/actions because there is no option to target choices (only entire field can be targeted by filters/actions).

This small modification won't affect rendering in admin panel but it will be very useful for the frontend.

**Comment by elliotcondon** [comment]
Hi @jmarceli 

Thanks for the topic. Can you elaborate on what CSS you are attempting to create with the extra span element?

Is it possible to use an `:after` or `:before:` rule?

I would like to avoid adding in extra elements if possible.

**Comment by jmarceli** [comment]
I've manage to achieve desired result with existing filters:
```
// allows for custom checkbox/radio styling on the frontend form
function add_tag_before_choice( $field ) {
	if( is_admin() ) {
    return $field;
  }

  // radio/checkbox field support
  if ( !empty( $field['choices'] ) ) {
    $field['choices'] = array_map(function($choice) {
      return '<span></span>' . $choice;
    }, $field['choices']);
  }

  // true_false field support
  if ( !empty( $field['message'] ) ) {
    $field['message'] = '<span></span>' . $field['message'];
  }

  return $field;
}

// type
add_filter('acf/load_field/type=radio', __NAMESPACE__ . '\\add_tag_before_choice');
add_filter('acf/load_field/type=checkbox', __NAMESPACE__ . '\\add_tag_before_choice');
add_filter('acf/load_field/type=true_false', __NAMESPACE__ . '\\add_tag_before_choice');
```

Used CSS:
```
.acf-field-checkbox .acf-input,
.acf-field-true-false .acf-input {
  $tick-color: #000;
  input {
    display: none;
  }
  input + span {
    position: relative;
    display:inline-block;
    width: 16px;
    height: 16px;
    border: 1px solid #000;
    padding: 0;
    background: #fff;;
    margin: 0 20px 0 -36px;
  }

  // tick right
  input:checked + span:before {
    transform: rotate(30deg);
    content: '';
    position: absolute;
    width: 2px;
    height: 10px;
    background-color:$tick-color;
    left: 8px;
    top: 2px;
  }

  // tick left
  input:checked + span:after {
    transform: rotate(45deg);
    content: '';
    position: absolute;
    width: 6px;
    height: 2px;
    background-color:$tick-color;
    left: 2px;
    top: 8px;
  }
}
```
I used similar CSS to make styleable radio buttons.

Here is the sample result (checkboxes) with "wide" browser support (IE 9+, FF, Safari, Chrome):
![image](https://cloud.githubusercontent.com/assets/4281333/19290878/0b84de52-9012-11e6-8414-9eccb825e071.png)

I see no other way to get a similar result without adding empty `<span>` element.

While it is achievable with `load_field` filter I think it may be the default markup for the frontend form (empty `<span>` shouldn't be a problem for less demanding frontend customizations).

**Comment by elliotcondon** [comment]
Hi @jmarceli 

Thanks for the reply. I can see what you are doing now.
Did you know that the `<label>` element surrounding the input has a class of 'selected' for the active one? Perhaps you could use this + some `:after` / `:before` rules instead of a span?

**Comment by jmarceli** [comment]
I've tried that one, but in order to "react" to the `checkbox:checked` state I need some element on the same level as the `input` (a sibling). In this case `<label>` will not work as I can't target parent elments with CSS.

**Comment by samjco** [comment]
@elliotcondon @jmarceli 
Actually what might be a better approach is:

css:
```css
/* The container */
.acf-checkbox-list label {
  display: block;
  position: relative;
  padding-left: 35px;
  margin-bottom: 12px;
  cursor: pointer;
  /*font-size: 16px;*/
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

/* Hide the browsers default checkbox */
.acf-checkbox-list label input[type=checkbox] {
  position: absolute;
  opacity: 0;
  cursor: pointer;
  height: 0;
  width: 0;
}

/* Create a custom checkbox */
.acf-styled-checkmark {
  position: absolute;
  top: 0;
  left: 0;
  height: 20px;
  width: 20px;
  background-color: #eee;
}

/* On mouse-over, add a grey background color */
.acf-checkbox-list label:hover input[type=checkbox] ~ .acf-styled-checkmark {
  background-color: #ccc;
}

/* When the checkbox is checked, add a blue background */
.acf-checkbox-list label input[type=checkbox]:checked ~ .acf-styled-checkmark {
  background-color: #2196F3;
}

/* Create the checkmark/indicator (hidden when not checked) */
.acf-styled-checkmark:after {
  content: "";
  position: absolute;
  display: none;
}

/* Show the checkmark when checked */
.acf-checkbox-list label input[type=checkbox]:checked ~ .acf-styled-checkmark:after {
  display: block;
}

/* Style the checkmark/indicator */
.acf-checkbox-list label .acf-styled-checkmark:after {
  left: 7px;
  top: 3px;
  width: 4px;
  height: 8px;
  border: solid white;
  border-width: 0 3px 3px 0;
  -webkit-transform: rotate(45deg);
  -ms-transform: rotate(45deg);
  transform: rotate(45deg);
}
ul {
    list-style-type: none;
}
```


**js:**

```
jQuery(document).ready(function($) {
$("<span class='acf-styled-checkmark'></span>").appendTo(".acf-field-checkbox .acf-input .acf-checkbox-list li label");
});

```

**Comment by samjco** [comment]
And for Radios:

CSS:
```css
/* The container */
.acf-radio-list label {
  display: block;
  position: relative;
  padding-left: 35px;
  margin-bottom: 12px;
  cursor: pointer;
  font-size: 16px;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

/* Hide the browsers default checkbox */
.acf-radio-list label input[type=radio] {
  position: absolute;
  opacity: 0;
  cursor: pointer;
  height: 0;
  width: 0;
}

/* Create a custom checkbox */
.acf-styled-radio {
  position: absolute;
  top: 0;
  left: 0;
  height: 20px;
  width: 20px;
  background-color: #eee;
  border-radius: 50%;
}

/* On mouse-over, add a grey background color */
.acf-radio-list label:hover input[type=radio] ~ .acf-styled-radio {
  background-color: #ccc;
}

/* When the checkbox is checked, add a blue background */
.acf-radio-list label input[type=radio]:checked ~ .acf-styled-radio {
  background-color: #2196F3;
}

/* Create the checkmark/indicator (hidden when not checked) */
.acf-styled-radio:after {
  content: "";
  position: absolute;
  display: none;
}

/* Show the checkmark when checked */
.acf-radio-list label input[type=radio]:checked ~ .acf-styled-radio:after {
  display: block;
}

/* Style the checkmark/indicator */
.acf-radio-list label .acf-styled-radio:after {
 	top: 6px;
	left: 6px;
	width: 8px;
	height: 8px;
	border-radius: 50%;
	background: white;
}
ul.acf-radio-list {
    list-style-type: none;
}
```

JS:
jQuery(document).ready(function($) {
$("<span class='acf-styled-checkmark'></span>").appendTo(".acf-field-checkbox .acf-input .acf-checkbox-list li label");
$("<span class='acf-styled-radio'></span>").appendTo(".acf-field-radio .acf-input .acf-radio-list li label");
});
